filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/workspace_data/stacktrace.log
    multiline:
      type: pattern
      pattern: "^\\s"
      negate: false
      match: after

output.logstash:
  hosts: ['logstash:5044']
