api.http.port: 9600
api.http.host: '0.0.0.0'

# Check if the configuration has changed and reloads the configuration whenever it is changed
config.reload.automatic: true

# to ensure events ordering and autodetect_column_names in CSV plugin
pipeline.workers: 1

# Select default main pipeline. If not specify, it will process events log in round-robin fashion
pipeline.id: 'csv_file'
path.config: '/usr/share/logstash/pipeline/csv_file.conf'
