- pipeline.id: simple
  path.config: '/usr/share/logstash/pipeline/simple.conf'
- pipeline.id: mutate
  path.config: '/usr/share/logstash/pipeline/mutate.conf'
- pipeline.id: codec_multiline
  path.config: '/usr/share/logstash/pipeline/codec_multiline.conf'
- pipeline.id: csv_file
  path.config: '/usr/share/logstash/pipeline/csv_file.conf'
- pipeline.id: demo_grok
  path.config: '/usr/share/logstash/pipeline/demo_grok.conf'
- pipeline.id: beat
  path.config: '/usr/share/logstash/pipeline/beat.conf'
